version: '3'

services:
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: python main.py